### ISSUE TITLE
no .sln or .vcxproj file

### ISSUE THREAD

**Issue by dylanbgamer** [elitepleb/that_one#1]
title says it all. I dont know how to build the solution without those files

**Comment by elitepleb** [comment]
That sounds like a personal problem? Maybe ask google how to create and add files to an empty project.
You can even drag and drop them if the dialog box is too tedious for you and there are plenty of plugins to auto generate the filters.
You might even learn something that way!

I'm not planning to add solutions files since this limits the amount of users to only those who could actually gain from it. And not those who have never even created even the simplest of projects themselves.

So uhh, [https://www.learncpp.com/](url) i guess...

**Comment by silentshotghost** [comment]
@dylanbgamer here he just copied nacl's source and renamed https://github.com/KaylinOwO/projectnacl
