### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by hero5jungle** [elitepleb/that_one#5]
The dll injects just fine. The menu pops up when I press insert. But the game crashes as soon as select the in game character.

**Comment by elitepleb** [comment]
I think the engine prediction never worked on the default debug build, try turning that off.
I haven't touched the cheat since the last commit, so i'm not aware of any other issue.

Try learning how to debug the cheat with attach mode to see where it crashed, If you tell me where it crashes i might even bother to reinstall tf2 and start working on the cheat again.

**Comment by hero5jungle** [comment]
Turning off engine prediction does work. Thank you. It doesn't crash anymore.
